from setuptools import setup, find_packages

setup(
    name='CVAT_Video_Annotation_Processor_',
    version='1.0.0',
    packages=find_packages(),
    install_requires=[
        'numpy',
        'opencv-python',
        'xmltodict',
        # Add any other dependencies here
    ],
    long_description='''CVAT Video Annotation Processor is a Python package for processing videos with annotations generated by CVAT (Computer Vision Annotation Tool). It provides functions for parsing XML annotations, extracting ROIs (Regions of Interest) from videos, and saving the processed videos with labeled ROIs. This package is useful for computer vision and machine learning projects that require processing annotated videos for training or analysis.''',
)
